### ISSUE TITLE
Websocket implementation

### ISSUE THREAD

**Issue by g-tejas** [parasyte/egui-tokio-example#1]
Hey, any idea how you would implement this for a websocket connection? I'd like to pass some messages from the websocket connection in a separate thread to the the GUI in the main thread, so it can plot some values from the websocket connection. How would I go about doing this?

Also, in the send_req function, where does the spawned thread live? I'm having some trouble understanding that, since i thought u'd have to spawn the thread in the main.rs main function

**Comment by parasyte** [comment]
> Also, in the send_req function, where does the spawned thread live? I'm having some trouble understanding that, since i thought u'd have to spawn the thread in the main.rs main function

`tokio::spawn` will spawn the task in the default runtime, which is created in the main function.

> Hey, any idea how you would implement this for a websocket connection? I'd like to pass some messages from the websocket connection in a separate thread to the the GUI in the main thread, so it can plot some values from the websocket connection. How would I go about doing this?

There shouldn't really be anything special to do... What have you tried?

You can spawn your websocket task when you are ready connect. How you interact with it is going to depend on which crate you are using. For instance, `tokio-tungstenite` gives you a `WebSocketStream` that you can poll in your GUI. If you don't want to poll the stream, you will need to provide interior mutability to your GUI state via `Arc<Mutex<T>>` or similar and update that state from within an async task that awaits the stream.

**Comment by g-tejas** [comment]
Ahh, thank you for the tips, i played around with it and managed to get it to work

Also, by polling do you mean creating a channel with sync::mpsc and sending the messages from the stream over the channel? If so, I tried both methods via Arc<Mutex<T>> and the mpsc channel method, and i think ill go with the mpsc because i think i might mess something up with the locks later on. 

Is there a point in this piece of code, I can just leave it out right? This was in your main.rs
```rust
// Execute the runtime in its own thread.
// The future doesn't have to do anything. In this example, it just sleeps forever.
std::thread::spawn(move || {
    rt.block_on(async {
        loop {
            tokio::time::sleep(Duration::from_secs(3600)).await;
        }
    })
});
```

Another question, I plan to have some UI for the user to select. a certain asset/security via a drop down, and press "Connect" so they can get data for that asset, is there a way I can kill the spawned thread once the user connects to a different thread? Is there a limit to how many threads u can spawn?

Thank you so much for answering my questions, i really appreciate it!

**Comment by parasyte** [comment]
Using a channel is a good method for sharing data between threads. Tokio's channel types should be preferred in async contexts, and they are trivial to integrate into sync contexts with e.g. `block_on`. Try to avoid `std` (and `crossbeam`) channels in `async` functions, because they can block and will cause many problems.

> Is there a point in this piece of code, I can just leave it out right? This was in your main.rs

IIRC that code was necessary to keep the runtime running, but it could have been something I misunderstood about Tokio.

> is there a way I can kill the spawned thread once the user connects to a different thread?

Managing thread lifecycles is completely up to you. Every task you spawn will have some kind of loop to keep it busy. E.g. loop over messages on an incoming websocket stream, and transfers those messages to another task over a channel. You can add a second channel for sending a "stop event" to the task. Then the loop changes to `select!` on two futures; the one for the websocket stream and the other for the "stop event" channel. When you get a stop event (which can be a unit struct if it doesn't need any information) you just `break` out of the loop, and that's it! You're done, the task will exit cleanly when the async function returns.

> Is there a limit to how many threads u can spawn?

There are limits, but you should not be able to reasonably hit them in the kind of app you are describing. You'll start to notice issues somewhere between 100,000 to 1,000,000 async tasks (maybe, it depends on what they are doing) or between 10,000 to 50,000 system threads (again, it depends what they are doing). If they are all sleeping, then you are really only limited by physical memory available in the system.
